[OBSDEF-15071] Fix table overflow
EMCECS/clarity-react pull request #246
Opened 2022-06-08 12:38 UTC by Bhatii

## Summary
This PR fixes:
- Overflow issue in table data

2022-06-08 13:54 UTC, akate1 requested changes
Defect 15071 is not related to this PR

2022-06-08 13:54 UTC, akate1 commented on src/datagrid/DataGrid.tsx
> +            <div className={ClassNames.DATAGRID}>
Datagrid Footer is broken due to some changes. Please don't add custom inline styles to fix it we need to fix original issue.

2022-06-09 06:06 UTC, akate1 reviewed
@Bhatii As we are reverting some changes from PR https://github.com/EMCECS/clarity-react/pull/244 to fix this issue. Please re-validate datagrid filter things

2022-06-09 06:06 UTC, akate1 commented on src/datagrid/DataGrid.tsx
> +            <div className={ClassNames.DATAGRID}>
@Bhatii along with this please also remove inline style for Daragrid header that u have added in PR https://github.com/EMCECS/clarity-react/pull/244

2022-06-10 06:36 UTC, Bhatii commented
Closed due to related to other bug.
New PR: https://github.com/EMCECS/clarity-react/pull/247

2022-06-10 06:36 UTC, closed without merging